### ISSUE TITLE
Decide if I want to use US data instead of rest of the world data. 

### ISSUE THREAD

**Issue by KarolinaChalupova** [KarolinaChalupova/DiplomaThesis#2]
Right now, I only have rest of world. 
@martinhronec : Is it worth it to do both US and rest of world? Or only US? Or only rest?
Considerations: 
- more data means more observations
- I suppose US data will be more clean in terms of less missing observations and more liquidity (but liquidity should be taken care of by your filter @martinhronec )

**Comment by martinhronec** [comment]
* we addressed question about "more data -> more observations" in OTMH paper
  * simple answer is, there are region-specific things and it does not necessarily help for the US prediction, it is better internationally simply because you have bigger universe
* US data are ugly as well
  * for the next steps, see #3

**Comment by barunik** [comment]
I would be careful with "more data => more observations" since we already know we have different behavior and dependencies in data. The literature is rather narrow, but OTMH shows  it quite well.

**Comment by KarolinaChalupova** [comment]
For now, I am doing only global excluding US so that the computations take less time. If there is time at the end, I can run US as well.
